require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1


Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
   Enabled: false
Metrics/MethodLength:
   Enabled: false
Lint/MissingSuper:
   Enabled: false